# Generated by Django 5.1.4 on 2024-12-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0005_alter_vinilo_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinilo',
            name='stock',
        ),
    ]
