# Generated by Django 5.1.4 on 2024-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0006_remove_vinilo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilo',
            name='stock',
            field=models.CharField(default='Sin información', max_length=255),
        ),
    ]
