# Generated by Django 5.1.4 on 2024-12-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0007_vinilo_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinilo',
            name='stock',
            field=models.CharField(max_length=255),
        ),
    ]
