# Generated by Django 5.1.4 on 2024-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyls', '0008_alter_vinilo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilo',
            name='enlace',
            field=models.URLField(default='https://default.url'),
        ),
    ]
