name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
          pip install safety==2.3.5

      - name: Ejecutar Bandit (SAST)
        run: |
          mkdir -p logs
          bandit -r . -x env,venv,__pycache__,.git -o logs/bandit_report.txt -f txt
          cat logs/bandit_report.txt
        continue-on-error: true

      - name: Ejecutar Safety (SCA)
        run: |
          safety check -r requirements.txt > logs/safety_report.txt
          cat logs/safety_report.txt
        continue-on-error: true

      - name: Ejecutar Semgrep (IAST)
        run: |
          pip install semgrep
          mkdir -p logs
          semgrep --config auto --json > logs/semgrep_report.json
          cat logs/semgrep_report.json
        continue-on-error: true

      - name: Ejecutar servidor Django en segundo plano
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10  # espera a que el servidor levante

      - name: Ejecutar OWASP ZAP (DAST)
        run: |
          docker pull owasp/zap2docker-stable
          mkdir -p logs
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://host.docker.internal:8000 -g gen.conf -r zap_report.html || true
        continue-on-error: true

      - name: Guardar informes como artifacts
        uses: actions/upload-artifact@v4
        with:
          name: informes-devsecops
          path: logs/

